[matrix]
m = 100
k = 100
n = 100
small_percision = 1
ratio = 4

[fifo]
capacity = 14
generation_cost = 10
accsess_cost = 2
seed_size = 1

[multiplication]
tile_h = 50
tile_w = 50
b_source = "fifo"

[cache]
block_size = 6
mem_cycles = 100
l1_size = 14
l1_cycles = 4
l1_assoc = 3
l2_size = 16
l2_cycles = 20
l2_assoc = 3
write_alloc = false
